version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: simplewebsite-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: donation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: simplewebsite-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/donation?schema=donation
      PORT: 3001
    ports:
      - "3001:3001"
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: simplewebsite-frontend
    depends_on:
      - backend
    environment:
      VITE_BASE_URL: http://localhost:3001/api/v1
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data:
    name: simplewebsite-postgres-data